# Recs 008: History-blend grid search (@5 metrics)

## Key Goal

Quantify whether history-aware query blending improves retrieval over raw query embedding using a same-user proxy task.

## Decision It Supports

Whether to introduce an optional history-blend mode in serving, and which parameter region is most promising.

## Primary Metrics

Hit@5, Recall@5, MAP@5, NDCG@5, and MRR (aggregated per-user with recs_004 semantics).

## Setup Notes

- Target/proxy: for each eval user, treat one liked review as query and other liked eval games as positives.
- Feature choice: query text + optional train-history blend from same user.
- Leakage guard: train history excludes query app and eval positives, and excludes train rows after query timestamp.
- Split strategy: eval split controlled by `RECS004_EVAL_SPLIT` (`val` default, `test` optional holdout).

In [1]:
from __future__ import annotations

import json
import math
import os
import time
from pathlib import Path
from itertools import product

import numpy as np
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

In [2]:
def _repo_root() -> Path:
    here = Path.cwd().resolve()
    for d in [here, *here.parents]:
        if (d / 'pyproject.toml').is_file():
            return d
    raise RuntimeError(f'Could not find repo root from cwd={here}')

REPO_ROOT = _repo_root()
PROCESSED = REPO_ROOT / 'data' / 'processed'
VAL_PARQUET = PROCESSED / 'steam_reviews_cleaned_english_val_norm.parquet'
TRAIN_PARQUET = PROCESSED / 'steam_reviews_cleaned_english_train_norm.parquet'
TEST_PARQUET = PROCESSED / 'steam_reviews_cleaned_english_test_norm.parquet'

split = os.environ.get('RECS004_EVAL_SPLIT', 'val').strip().lower()
if split == 'test':
    EVAL_PARQUET = TEST_PARQUET
    EVAL_SPLIT_NAME = 'test'
elif split == 'train':
    EVAL_PARQUET = TRAIN_PARQUET
    EVAL_SPLIT_NAME = 'train'
else:
    EVAL_PARQUET = VAL_PARQUET if VAL_PARQUET.is_file() else TRAIN_PARQUET
    EVAL_SPLIT_NAME = 'val' if EVAL_PARQUET == VAL_PARQUET else 'train'

for p in (EVAL_PARQUET, TRAIN_PARQUET):
    if not p.is_file():
        raise FileNotFoundError(p)

from steam_review_ml.recommender.retrieve import ContentRetriever
retriever = ContentRetriever()
indexed_apps = set(retriever.app_ids.tolist())

print('Eval split:', EVAL_SPLIT_NAME, '|', EVAL_PARQUET.name)
print('Indexed games:', len(indexed_apps))

Eval split: val | steam_reviews_cleaned_english_val_norm.parquet
Indexed games: 315

In [3]:
# Runtime + grid config (requested): medium grid, 5000-user cap
from steam_review_ml.constants import PROJECT_RANDOM_SEED

RNG_SEED = PROJECT_RANDOM_SEED
MAX_USERS = 1000
MIN_REVIEW_CHARS = 30
MAX_HISTORY_ROWS_PER_USER = 200
TOP_K = 5
RETRIEVAL_K = 200  # used for MRR scan depth

ALPHAS = [0.05, 0.10, 0.20, 0.30, 0.40]
MIN_SIMS = [0.0, 0.1, 0.2, 0.3, 0.4]
HISTORY_TOP_KS = [1, 2, 3, 5]
# ALPHAS = [0.05, 0.10,]
# MIN_SIMS = [0.0, 0.1,]
# HISTORY_TOP_KS = [1, ]

GRID = [
    {'history_alpha': a, 'history_min_similarity': s, 'history_top_k': t}
    for a, s, t in product(ALPHAS, MIN_SIMS, HISTORY_TOP_KS)
]

print('Grid size:', len(GRID))

Grid size: 100

In [4]:
def recall_at_k(ranked_app_ids: np.ndarray, positives: set[int], k: int) -> float:
    if not positives:
        return float('nan')
    top = set(int(a) for a in ranked_app_ids[:k])
    return len(top & positives) / len(positives)

def hit_rate_at_k(ranked_app_ids: np.ndarray, positives: set[int], k: int) -> float:
    top = set(int(a) for a in ranked_app_ids[:k])
    return 1.0 if (top & positives) else 0.0

def average_precision_at_k(ranked_app_ids: np.ndarray, positives: set[int], k: int) -> float:
    if not positives:
        return float('nan')
    hits = 0
    prec_sum = 0.0
    for rank, app_id in enumerate(ranked_app_ids[:k].tolist(), start=1):
        if int(app_id) in positives:
            hits += 1
            prec_sum += hits / rank
    return prec_sum / len(positives)

def ndcg_at_k(ranked_app_ids: np.ndarray, positives: set[int], k: int) -> float:
    if not positives:
        return float('nan')
    gains = [1.0 if int(a) in positives else 0.0 for a in ranked_app_ids[:k]]

    def dcg(vals: list[float]) -> float:
        return sum(rel / math.log2(idx + 2) for idx, rel in enumerate(vals))

    ideal_len = min(len(positives), k)
    ideal = [1.0] * ideal_len + [0.0] * max(0, k - ideal_len)
    idcg = dcg(ideal)
    if idcg <= 1e-12:
        return 0.0
    return dcg(gains) / idcg

def mrr(ranked_app_ids: np.ndarray, positives: set[int]) -> float:
    if not positives:
        return float('nan')
    for rank, app_id in enumerate(ranked_app_ids.tolist(), start=1):
        if int(app_id) in positives:
            return 1.0 / rank
    return 0.0

def summarize(metric_lists: dict[str, list[float]]) -> dict[str, float]:
    out = {}
    for metric, vals in metric_lists.items():
        arr = np.asarray(vals, dtype=np.float64)
        if metric.startswith(('recall', 'map', 'ndcg')) or metric == 'mrr':
            out[metric] = float(np.nanmean(arr))
        else:
            out[metric] = float(arr.mean())
    return out

In [5]:
rng = np.random.default_rng(RNG_SEED)
USER_COL = 'author.steamid'
TIME_COL = 'timestamp_created'
usecols = [USER_COL, 'app_id', 'review', 'recommended', TIME_COL]

def _load_split_df(path: Path) -> pd.DataFrame:
    d = pd.read_parquet(path, columns=usecols)
    d = d.loc[d['recommended'] == 1].copy()
    d['review'] = d['review'].fillna('').astype(str)
    d = d[d['review'].str.len() >= MIN_REVIEW_CHARS]
    d = d[d['app_id'].isin(indexed_apps)]
    d['ts'] = pd.to_numeric(d[TIME_COL], errors='coerce')
    d = d.dropna(subset=['ts'])
    d['ts'] = d['ts'].astype(np.float64)
    return d

df_eval = _load_split_df(EVAL_PARQUET)
df_train = _load_split_df(TRAIN_PARQUET)

uc = df_eval.groupby(USER_COL)['app_id'].nunique()
multi = uc[uc >= 2].index
multi = pd.Index(rng.permutation(multi.values)[: min(len(multi), MAX_USERS)])

examples = []
for uid in multi:
    sub_v = df_eval[df_eval[USER_COL] == uid]
    sub_t = df_train[df_train[USER_COL] == uid]
    apps = sub_v['app_id'].unique().tolist()

    q_app = int(rng.choice(apps))
    rows_q = sub_v[sub_v['app_id'] == q_app]
    row_q = rows_q.iloc[int(rng.integers(0, len(rows_q)))]

    positives = {int(a) for a in apps if int(a) != q_app}
    if not positives:
        continue

    query_text = str(row_q['review'])
    query_ts = float(row_q['ts'])
    blocklist = positives | {q_app}

    history_rows = []
    for _, r in sub_t.iterrows():
        aid = int(r['app_id'])
        ts = float(r['ts'])
        if aid in blocklist:
            continue
        if ts > query_ts:
            continue
        history_rows.append(str(r['review']))

    rng.shuffle(history_rows)
    if len(history_rows) > MAX_HISTORY_ROWS_PER_USER:
        history_rows = history_rows[:MAX_HISTORY_ROWS_PER_USER]

    examples.append({
        'steamid': uid,
        'query_app_id': q_app,
        'query_text': query_text,
        'positives': positives,
        'history_texts': history_rows,
    })

print('Examples:', len(examples))
if examples:
    print('History texts per user (median):', int(np.median([len(e['history_texts']) for e in examples])))

Examples: 1000
History texts per user (median): 0

In [6]:
def _fmt_duration(seconds: float) -> str:
    seconds = max(0, int(seconds))
    h, rem = divmod(seconds, 3600)
    m, s = divmod(rem, 60)
    if h > 0:
        return f"{h}h {m:02d}m {s:02d}s"
    return f"{m:02d}m {s:02d}s"


def evaluate_config(
    cfg: dict[str, float | int],
    *,
    progress_every_users: int = 500,
    cfg_idx: int | None = None,
    total_cfgs: int | None = None,
) -> dict[str, float]:
    agg = {'hit@5': [], 'recall@5': [], 'map@5': [], 'ndcg@5': [], 'mrr': []}
    n_examples = len(examples)
    start_cfg = time.perf_counter()

    if cfg_idx is not None and total_cfgs is not None:
        print(
            f"[Config {cfg_idx}/{total_cfgs}] start "
            f"alpha={cfg['history_alpha']}, min_sim={cfg['history_min_similarity']}, top_k={cfg['history_top_k']}"
        )

    for i, ex in enumerate(examples, start=1):
        hits = retriever.top_k(
            ex['query_text'],
            k=RETRIEVAL_K,
            structured=False,
            exclude_app_ids={int(ex['query_app_id'])},
            history_texts=ex['history_texts'],
            history_blend_alpha=float(cfg['history_alpha']),
            history_top_k=int(cfg['history_top_k']),
            history_min_similarity=float(cfg['history_min_similarity']),
        )
        ranked = hits['app_id'].to_numpy(dtype=np.int64)
        pos = ex['positives']

        agg['hit@5'].append(hit_rate_at_k(ranked, pos, TOP_K))
        agg['recall@5'].append(recall_at_k(ranked, pos, TOP_K))
        agg['map@5'].append(average_precision_at_k(ranked, pos, TOP_K))
        agg['ndcg@5'].append(ndcg_at_k(ranked, pos, TOP_K))
        agg['mrr'].append(mrr(ranked, pos))

        if progress_every_users > 0 and (i % progress_every_users == 0 or i == n_examples):
            elapsed = time.perf_counter() - start_cfg
            done_pct = 100.0 * i / n_examples
            rate = elapsed / i
            eta = rate * (n_examples - i)
            print(
                f"    users {i}/{n_examples} ({done_pct:5.1f}%) | "
                f"elapsed {_fmt_duration(elapsed)} | eta {_fmt_duration(eta)}"
            )

    return summarize(agg)


# Baseline (raw query, no history blend)
baseline_cfg = {'history_alpha': 0.0, 'history_min_similarity': 0.2, 'history_top_k': 3}
print('Computing baseline config...')
start_all = time.perf_counter()
baseline_metrics = evaluate_config(baseline_cfg, progress_every_users=1000)
print('Baseline done:', baseline_metrics)

rows = []
total_cfgs = len(GRID)
for idx, cfg in enumerate(GRID, start=1):
    cfg_start = time.perf_counter()
    metrics = evaluate_config(
        cfg,
        progress_every_users=1000,
        cfg_idx=idx,
        total_cfgs=total_cfgs,
    )
    row = {**cfg, **metrics}
    for m in ['hit@5', 'recall@5', 'map@5', 'ndcg@5', 'mrr']:
        row[f'delta_{m}'] = row[m] - baseline_metrics[m]
    rows.append(row)

    cfg_elapsed = time.perf_counter() - cfg_start
    all_elapsed = time.perf_counter() - start_all
    avg_per_cfg = all_elapsed / idx
    remaining = avg_per_cfg * (total_cfgs - idx)
    print(
        f"[Config {idx}/{total_cfgs}] done in {_fmt_duration(cfg_elapsed)} | "
        f"total {_fmt_duration(all_elapsed)} | eta {_fmt_duration(remaining)}"
    )

grid_df = pd.DataFrame(rows).sort_values('map@5', ascending=False).reset_index(drop=True)

print('Baseline (alpha=0):', baseline_metrics)
print('Grid search complete. Total runtime:', _fmt_duration(time.perf_counter() - start_all))
display(grid_df.head(20))

Computing baseline config...

2026-04-21 18:24:05.989839: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1776810245.999423  275935 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1776810246.002282  275935 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1776810246.010159  275935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776810246.010172  275935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776810246.010174  275935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1776810246.010175  275935 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
/home/ryanr/miniconda3/envs/tf_condaforge/lib/python3.11/site-packages/tensorflow_hub/__init__.py:61: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import parse_version
I0000 00:00:1776810248.281405  275935 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5199 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 5070 Laptop GPU, pci bus id: 0000:02:00.0, compute capability: 12.0

    users 1000/1000 (100.0%) | elapsed 00m 21s | eta 00m 00s
Baseline done: {'hit@5': 0.064, 'recall@5': 0.064, 'map@5': 0.03483333333333333, 'ndcg@5': 0.041976874058512165, 'mrr': 0.050136731386834894}
[Config 1/100] start alpha=0.05, min_sim=0.0, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 1/100] done in 00m 10s | total 00m 31s | eta 52m 22s
[Config 2/100] start alpha=0.05, min_sim=0.0, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 2/100] done in 00m 10s | total 00m 42s | eta 34m 39s
[Config 3/100] start alpha=0.05, min_sim=0.0, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 3/100] done in 00m 12s | total 00m 54s | eta 29m 23s
[Config 4/100] start alpha=0.05, min_sim=0.0, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 4/100] done in 00m 11s | total 01m 06s | eta 26m 36s
[Config 5/100] start alpha=0.05, min_sim=0.1, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 5/100] done in 00m 11s | total 01m 17s | eta 24m 38s
[Config 6/100] start alpha=0.05, min_sim=0.1, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 6/100] done in 00m 09s | total 01m 27s | eta 22m 54s
[Config 7/100] start alpha=0.05, min_sim=0.1, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 7/100] done in 00m 09s | total 01m 37s | eta 21m 35s
[Config 8/100] start alpha=0.05, min_sim=0.1, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 8/100] done in 00m 10s | total 01m 47s | eta 20m 38s
[Config 9/100] start alpha=0.05, min_sim=0.2, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 9/100] done in 00m 10s | total 01m 58s | eta 19m 58s
[Config 10/100] start alpha=0.05, min_sim=0.2, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 10/100] done in 00m 11s | total 02m 09s | eta 19m 29s
[Config 11/100] start alpha=0.05, min_sim=0.2, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 11/100] done in 00m 10s | total 02m 20s | eta 18m 58s
[Config 12/100] start alpha=0.05, min_sim=0.2, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 12/100] done in 00m 11s | total 02m 32s | eta 18m 36s
[Config 13/100] start alpha=0.05, min_sim=0.3, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 13/100] done in 00m 11s | total 02m 43s | eta 18m 12s
[Config 14/100] start alpha=0.05, min_sim=0.3, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 14/100] done in 00m 11s | total 02m 54s | eta 17m 51s
[Config 15/100] start alpha=0.05, min_sim=0.3, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 15/100] done in 00m 10s | total 03m 05s | eta 17m 30s
[Config 16/100] start alpha=0.05, min_sim=0.3, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 16/100] done in 00m 11s | total 03m 16s | eta 17m 13s
[Config 17/100] start alpha=0.05, min_sim=0.4, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 17/100] done in 00m 10s | total 03m 26s | eta 16m 50s
[Config 18/100] start alpha=0.05, min_sim=0.4, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 18/100] done in 00m 09s | total 03m 36s | eta 16m 28s
[Config 19/100] start alpha=0.05, min_sim=0.4, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 19/100] done in 00m 10s | total 03m 47s | eta 16m 08s
[Config 20/100] start alpha=0.05, min_sim=0.4, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 20/100] done in 00m 10s | total 03m 57s | eta 15m 51s
[Config 21/100] start alpha=0.1, min_sim=0.0, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 21/100] done in 00m 09s | total 04m 07s | eta 15m 30s
[Config 22/100] start alpha=0.1, min_sim=0.0, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 22/100] done in 00m 09s | total 04m 16s | eta 15m 10s
[Config 23/100] start alpha=0.1, min_sim=0.0, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 23/100] done in 00m 10s | total 04m 27s | eta 14m 55s
[Config 24/100] start alpha=0.1, min_sim=0.0, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 24/100] done in 00m 10s | total 04m 37s | eta 14m 38s
[Config 25/100] start alpha=0.1, min_sim=0.1, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 25/100] done in 00m 09s | total 04m 47s | eta 14m 21s
[Config 26/100] start alpha=0.1, min_sim=0.1, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 26/100] done in 00m 09s | total 04m 56s | eta 14m 03s
[Config 27/100] start alpha=0.1, min_sim=0.1, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 27/100] done in 00m 10s | total 05m 06s | eta 13m 49s
[Config 28/100] start alpha=0.1, min_sim=0.1, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 28/100] done in 00m 09s | total 05m 16s | eta 13m 33s
[Config 29/100] start alpha=0.1, min_sim=0.2, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 29/100] done in 00m 09s | total 05m 26s | eta 13m 18s
[Config 30/100] start alpha=0.1, min_sim=0.2, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 30/100] done in 00m 09s | total 05m 35s | eta 13m 03s
[Config 31/100] start alpha=0.1, min_sim=0.2, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 31/100] done in 00m 09s | total 05m 45s | eta 12m 48s
[Config 32/100] start alpha=0.1, min_sim=0.2, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 32/100] done in 00m 09s | total 05m 54s | eta 12m 33s
[Config 33/100] start alpha=0.1, min_sim=0.3, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 33/100] done in 00m 10s | total 06m 04s | eta 12m 20s
[Config 34/100] start alpha=0.1, min_sim=0.3, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 34/100] done in 00m 09s | total 06m 14s | eta 12m 06s
[Config 35/100] start alpha=0.1, min_sim=0.3, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 35/100] done in 00m 09s | total 06m 24s | eta 11m 53s
[Config 36/100] start alpha=0.1, min_sim=0.3, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 36/100] done in 00m 09s | total 06m 34s | eta 11m 40s
[Config 37/100] start alpha=0.1, min_sim=0.4, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 37/100] done in 00m 10s | total 06m 44s | eta 11m 29s
[Config 38/100] start alpha=0.1, min_sim=0.4, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 38/100] done in 00m 11s | total 06m 56s | eta 11m 18s
[Config 39/100] start alpha=0.1, min_sim=0.4, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 39/100] done in 00m 10s | total 07m 06s | eta 11m 07s
[Config 40/100] start alpha=0.1, min_sim=0.4, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 40/100] done in 00m 11s | total 07m 18s | eta 10m 57s
[Config 41/100] start alpha=0.2, min_sim=0.0, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 41/100] done in 00m 11s | total 07m 30s | eta 10m 47s
[Config 42/100] start alpha=0.2, min_sim=0.0, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 42/100] done in 00m 10s | total 07m 40s | eta 10m 35s
[Config 43/100] start alpha=0.2, min_sim=0.0, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 43/100] done in 00m 09s | total 07m 50s | eta 10m 23s
[Config 44/100] start alpha=0.2, min_sim=0.0, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 44/100] done in 00m 10s | total 08m 00s | eta 10m 11s
[Config 45/100] start alpha=0.2, min_sim=0.1, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 45/100] done in 00m 09s | total 08m 10s | eta 09m 59s
[Config 46/100] start alpha=0.2, min_sim=0.1, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 46/100] done in 00m 09s | total 08m 19s | eta 09m 46s
[Config 47/100] start alpha=0.2, min_sim=0.1, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 47/100] done in 00m 09s | total 08m 29s | eta 09m 34s
[Config 48/100] start alpha=0.2, min_sim=0.1, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 48/100] done in 00m 09s | total 08m 39s | eta 09m 22s
[Config 49/100] start alpha=0.2, min_sim=0.2, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 49/100] done in 00m 09s | total 08m 49s | eta 09m 10s
[Config 50/100] start alpha=0.2, min_sim=0.2, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 50/100] done in 00m 09s | total 08m 59s | eta 08m 59s
[Config 51/100] start alpha=0.2, min_sim=0.2, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 51/100] done in 00m 09s | total 09m 09s | eta 08m 47s
[Config 52/100] start alpha=0.2, min_sim=0.2, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 52/100] done in 00m 09s | total 09m 18s | eta 08m 35s
[Config 53/100] start alpha=0.2, min_sim=0.3, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 53/100] done in 00m 09s | total 09m 28s | eta 08m 24s
[Config 54/100] start alpha=0.2, min_sim=0.3, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 54/100] done in 00m 09s | total 09m 37s | eta 08m 12s
[Config 55/100] start alpha=0.2, min_sim=0.3, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 08s | eta 00m 00s
[Config 55/100] done in 00m 08s | total 09m 46s | eta 07m 59s
[Config 56/100] start alpha=0.2, min_sim=0.3, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 56/100] done in 00m 09s | total 09m 55s | eta 07m 48s
[Config 57/100] start alpha=0.2, min_sim=0.4, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 57/100] done in 00m 10s | total 10m 05s | eta 07m 37s
[Config 58/100] start alpha=0.2, min_sim=0.4, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 58/100] done in 00m 12s | total 10m 18s | eta 07m 27s
[Config 59/100] start alpha=0.2, min_sim=0.4, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 59/100] done in 00m 12s | total 10m 30s | eta 07m 18s
[Config 60/100] start alpha=0.2, min_sim=0.4, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 60/100] done in 00m 12s | total 10m 43s | eta 07m 08s
[Config 61/100] start alpha=0.3, min_sim=0.0, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 61/100] done in 00m 12s | total 10m 56s | eta 06m 59s
[Config 62/100] start alpha=0.3, min_sim=0.0, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 14s | eta 00m 00s
[Config 62/100] done in 00m 14s | total 11m 10s | eta 06m 50s
[Config 63/100] start alpha=0.3, min_sim=0.0, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 63/100] done in 00m 11s | total 11m 21s | eta 06m 40s
[Config 64/100] start alpha=0.3, min_sim=0.0, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 64/100] done in 00m 10s | total 11m 32s | eta 06m 29s
[Config 65/100] start alpha=0.3, min_sim=0.1, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 65/100] done in 00m 10s | total 11m 43s | eta 06m 18s
[Config 66/100] start alpha=0.3, min_sim=0.1, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 66/100] done in 00m 10s | total 11m 53s | eta 06m 07s
[Config 67/100] start alpha=0.3, min_sim=0.1, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 67/100] done in 00m 10s | total 12m 04s | eta 05m 56s
[Config 68/100] start alpha=0.3, min_sim=0.1, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 68/100] done in 00m 10s | total 12m 15s | eta 05m 46s
[Config 69/100] start alpha=0.3, min_sim=0.2, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 69/100] done in 00m 10s | total 12m 26s | eta 05m 35s
[Config 70/100] start alpha=0.3, min_sim=0.2, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 70/100] done in 00m 10s | total 12m 36s | eta 05m 24s
[Config 71/100] start alpha=0.3, min_sim=0.2, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 71/100] done in 00m 10s | total 12m 47s | eta 05m 13s
[Config 72/100] start alpha=0.3, min_sim=0.2, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 72/100] done in 00m 10s | total 12m 57s | eta 05m 02s
[Config 73/100] start alpha=0.3, min_sim=0.3, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 16s | eta 00m 00s
[Config 73/100] done in 00m 16s | total 13m 14s | eta 04m 53s
[Config 74/100] start alpha=0.3, min_sim=0.3, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 74/100] done in 00m 11s | total 13m 26s | eta 04m 43s
[Config 75/100] start alpha=0.3, min_sim=0.3, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 75/100] done in 00m 11s | total 13m 37s | eta 04m 32s
[Config 76/100] start alpha=0.3, min_sim=0.3, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 76/100] done in 00m 12s | total 13m 49s | eta 04m 21s
[Config 77/100] start alpha=0.3, min_sim=0.4, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 77/100] done in 00m 12s | total 14m 01s | eta 04m 11s
[Config 78/100] start alpha=0.3, min_sim=0.4, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 78/100] done in 00m 11s | total 14m 13s | eta 04m 00s
[Config 79/100] start alpha=0.3, min_sim=0.4, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 79/100] done in 00m 09s | total 14m 22s | eta 03m 49s
[Config 80/100] start alpha=0.3, min_sim=0.4, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 80/100] done in 00m 09s | total 14m 31s | eta 03m 37s
[Config 81/100] start alpha=0.4, min_sim=0.0, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 08s | eta 00m 00s
[Config 81/100] done in 00m 08s | total 14m 40s | eta 03m 26s
[Config 82/100] start alpha=0.4, min_sim=0.0, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 08s | eta 00m 00s
[Config 82/100] done in 00m 08s | total 14m 49s | eta 03m 15s
[Config 83/100] start alpha=0.4, min_sim=0.0, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 83/100] done in 00m 09s | total 14m 59s | eta 03m 04s
[Config 84/100] start alpha=0.4, min_sim=0.0, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 84/100] done in 00m 09s | total 15m 09s | eta 02m 53s
[Config 85/100] start alpha=0.4, min_sim=0.1, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 85/100] done in 00m 09s | total 15m 18s | eta 02m 42s
[Config 86/100] start alpha=0.4, min_sim=0.1, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 86/100] done in 00m 09s | total 15m 27s | eta 02m 31s
[Config 87/100] start alpha=0.4, min_sim=0.1, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 87/100] done in 00m 09s | total 15m 37s | eta 02m 20s
[Config 88/100] start alpha=0.4, min_sim=0.1, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 88/100] done in 00m 09s | total 15m 46s | eta 02m 09s
[Config 89/100] start alpha=0.4, min_sim=0.2, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 09s | eta 00m 00s
[Config 89/100] done in 00m 09s | total 15m 56s | eta 01m 58s
[Config 90/100] start alpha=0.4, min_sim=0.2, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 90/100] done in 00m 10s | total 16m 06s | eta 01m 47s
[Config 91/100] start alpha=0.4, min_sim=0.2, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 12s | eta 00m 00s
[Config 91/100] done in 00m 12s | total 16m 19s | eta 01m 36s
[Config 92/100] start alpha=0.4, min_sim=0.2, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 92/100] done in 00m 11s | total 16m 30s | eta 01m 26s
[Config 93/100] start alpha=0.4, min_sim=0.3, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 93/100] done in 00m 11s | total 16m 41s | eta 01m 15s
[Config 94/100] start alpha=0.4, min_sim=0.3, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 94/100] done in 00m 11s | total 16m 53s | eta 01m 04s
[Config 95/100] start alpha=0.4, min_sim=0.3, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 95/100] done in 00m 11s | total 17m 05s | eta 00m 53s
[Config 96/100] start alpha=0.4, min_sim=0.3, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 10s | eta 00m 00s
[Config 96/100] done in 00m 10s | total 17m 15s | eta 00m 43s
[Config 97/100] start alpha=0.4, min_sim=0.4, top_k=1
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 97/100] done in 00m 11s | total 17m 27s | eta 00m 32s
[Config 98/100] start alpha=0.4, min_sim=0.4, top_k=2
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 98/100] done in 00m 11s | total 17m 39s | eta 00m 21s
[Config 99/100] start alpha=0.4, min_sim=0.4, top_k=3
    users 1000/1000 (100.0%) | elapsed 00m 14s | eta 00m 00s
[Config 99/100] done in 00m 14s | total 17m 53s | eta 00m 10s
[Config 100/100] start alpha=0.4, min_sim=0.4, top_k=5
    users 1000/1000 (100.0%) | elapsed 00m 11s | eta 00m 00s
[Config 100/100] done in 00m 11s | total 18m 05s | eta 00m 00s
Baseline (alpha=0): {'hit@5': 0.064, 'recall@5': 0.064, 'map@5': 0.03483333333333333, 'ndcg@5': 0.041976874058512165, 'mrr': 0.050136731386834894}
Grid search complete. Total runtime: 18m 05s

    history_alpha  history_min_similarity  history_top_k  hit@5  recall@5     map@5    ndcg@5       mrr  delta_hit@5  delta_recall@5  delta_map@5  delta_ndcg@5  delta_mrr
0            0.05                     0.0              1  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
1            0.05                     0.0              2  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
2            0.05                     0.0              3  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
3            0.05                     0.0              5  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
4            0.05                     0.1              1  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
5            0.05                     0.1              2  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
6            0.05                     0.1              3  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
7            0.05                     0.1              5  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
8            0.05                     0.2              1  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
9            0.05                     0.2              2  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
10           0.05                     0.2              3  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
11           0.05                     0.2              5  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
12           0.05                     0.3              1  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
13           0.05                     0.3              2  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
14           0.05                     0.3              3  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
15           0.05                     0.3              5  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
16           0.05                     0.4              1  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
17           0.05                     0.4              2  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
18           0.05                     0.4              3  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0
19           0.05                     0.4              5  0.064     0.064  0.034833  0.041977  0.050137          0.0             0.0          0.0           0.0        0.0

In [7]:
metric_cols = ['hit@5', 'recall@5', 'map@5', 'ndcg@5', 'mrr']
best_per_metric = []
for m in metric_cols:
    r = grid_df.sort_values(m, ascending=False).iloc[0]
    best_per_metric.append({
        'metric': m,
        'best_value': float(r[m]),
        'history_alpha': float(r['history_alpha']),
        'history_min_similarity': float(r['history_min_similarity']),
        'history_top_k': int(r['history_top_k']),
        'delta_vs_baseline': float(r[f'delta_{m}']),
    })

best_df = pd.DataFrame(best_per_metric)
display(best_df)

OUT = REPO_ROOT / 'artifacts' / 'recs' / 'eval_history_blend_gridsearch_at5.csv'
grid_df.to_csv(OUT, index=False)
print('Wrote:', OUT)

     metric  best_value  history_alpha  history_min_similarity  history_top_k  delta_vs_baseline
0     hit@5    0.064000           0.05                     0.0              1                0.0
1  recall@5    0.064000           0.05                     0.0              1                0.0
2     map@5    0.034833           0.05                     0.0              1                0.0
3    ndcg@5    0.041977           0.05                     0.0              1                0.0
4       mrr    0.050137           0.05                     0.0              1                0.0

Wrote: /home/ryanr/workspace/steam_recommendations/artifacts/recs/eval_history_blend_gridsearch_at5.csv