# IGDB 002: IGDB field review

**Per-column EDA on pipeline IGDB artifacts**

Profiles all IGDB game columns in `igdb_games.parquet`. Field docs: [`field_docs.py`](../../src/steam_review_ml/igdb/field_docs.py).

# Executive Summary

**Question:**  
For each IGDB game column in our joined parquet, what is the **value shape**, **typical content**, and **likely v2 utility**?

**Result:**  
_Update after running the per-field section._

**Recommendation / Decision:**  
_Tag which fields to wire for V2a vs V2b vs defer._

# Data Sources

**Primary:** `artifacts/igdb/igdb_games.parquet` (from `recs_job_igdb_games.py`)

**Join context:** `artifacts/igdb/igdb_join_report.json` (optional)

**Pipeline refresh:** `python scripts/recs_job_igdb_games.py configs/recs_job_igdb_games.json`

# Notebook Roadmap

1. Setup + load parquet
2. Overview table (all IGDB fields)
3. Per-field profiles
4. Key Findings (manual)

# Analysis

## Setup

In [1]:
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
from IPython.display import Markdown, display

from steam_review_ml.igdb.constants import IGDB_GAMES_PARQUET, STEAM_JOIN_COLS, V2_CORE_FIELDS
from steam_review_ml.igdb.field_docs import GAME_FIELD_DOCS, V2_FIELD_NOTES

REPO_ROOT = next(p for p in [Path.cwd(), *Path.cwd().parents] if (p / "pyproject.toml").is_file())
IGDB_DIR = REPO_ROOT / "artifacts/igdb"
PARQUET_PATH = IGDB_DIR / IGDB_GAMES_PARQUET
REPORT_PATH = IGDB_DIR / "igdb_join_report.json"

SAMPLE_APP_IDS = [753420, 646910, 512900]

print(f"REPO_ROOT={REPO_ROOT}")

REPO_ROOT=/home/ryanr/workspace/steam_recommendations

In [2]:
if not PARQUET_PATH.is_file():
    raise FileNotFoundError(
        f"Missing {PARQUET_PATH}. Run:\n"
        "  python scripts/recs_job_igdb_games.py configs/recs_job_igdb_games.json"
    )

df = pd.read_parquet(PARQUET_PATH)
join_report = json.loads(REPORT_PATH.read_text(encoding="utf-8")) if REPORT_PATH.is_file() else {}

IGDB_GAME_FIELDS = sorted(c for c in df.columns if c not in STEAM_JOIN_COLS and c != "igdb_name")
absent_from_parquet = sorted(set(GAME_FIELD_DOCS) - set(IGDB_GAME_FIELDS) - {"name"})

print(f"rows={len(df)} cols={len(df.columns)}")
print(f"IGDB_GAME_FIELDS ({len(IGDB_GAME_FIELDS)}): {IGDB_GAME_FIELDS}")
print(f"catalog match rate: {join_report.get('match_rate', 'n/a')}")
if absent_from_parquet:
    print(f"Fields in GAME_FIELD_DOCS but not in parquet: {absent_from_parquet}")

rows=314 cols=59
IGDB_GAME_FIELDS (54): ['age_ratings', 'aggregated_rating', 'aggregated_rating_count', 'alternative_names', 'artworks', 'bundles', 'checksum', 'collections', 'cover', 'created_at', 'dlcs', 'expanded_games', 'expansions', 'external_games', 'first_release_date', 'franchise', 'franchises', 'game_engines', 'game_localizations', 'game_modes', 'game_status', 'game_type', 'genres', 'hypes', 'involved_companies', 'keywords', 'language_supports', 'multiplayer_modes', 'parent_game', 'platforms', 'player_perspectives', 'ports', 'rating', 'rating_count', 'release_dates', 'remakes', 'remasters', 'screenshots', 'similar_games', 'slug', 'standalone_expansions', 'status', 'storyline', 'summary', 'tags', 'themes', 'total_rating', 'total_rating_count', 'updated_at', 'url', 'version_parent', 'version_title', 'videos', 'websites']
catalog match rate: 0.9968253968253968
Fields in GAME_FIELD_DOCS but not in parquet: ['category', 'collection', 'follows', 'forks']

In [3]:
def igdb_field_doc(field: str) -> dict[str, str]:
    doc = GAME_FIELD_DOCS.get(field, {})
    return {
        "igdb_type": doc.get("type", ""),
        "igdb_description": doc.get("description", ""),
        "deprecated": doc.get("deprecated", False),
        "v2_note": V2_FIELD_NOTES.get(field, ""),
    }


def field_populated(value: Any) -> bool:
    if value is None:
        return False
    try:
        if pd.isna(value):
            return False
    except (TypeError, ValueError):
        pass
    if isinstance(value, str):
        return bool(value.strip())
    if isinstance(value, (list, dict, set, tuple, np.ndarray)):
        return len(value) > 0
    return True


def _as_list(value: Any) -> list[Any]:
    if value is None:
        return []
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, (list, tuple, set)):
        return list(value)
    try:
        if pd.isna(value):
            return []
    except (TypeError, ValueError):
        pass
    return [value]


def value_kind(value: Any) -> str:
    if not field_populated(value):
        return "empty"
    if isinstance(value, str):
        return "string"
    if isinstance(value, (int, np.integer)):
        return "integer"
    if isinstance(value, (float, np.floating)):
        return "float"
    if isinstance(value, np.ndarray):
        if value.ndim == 0:
            return value_kind(value.item())
        return "id_list" if np.issubdtype(value.dtype, np.integer) else "array"
    if isinstance(value, list):
        return "id_list" if value and all(isinstance(x, (int, np.integer)) for x in value) else "list"
    return type(value).__name__


def profile_column(series: pd.Series) -> dict[str, Any]:
    populated = series.map(field_populated)
    populated_s = series.loc[populated]
    kinds = populated_s.map(value_kind)
    kind_mode = kinds.mode().iloc[0] if len(kinds) else "empty"

    doc = igdb_field_doc(str(series.name))
    out: dict[str, Any] = {
        "field": series.name,
        "dtype": str(series.dtype),
        "coverage_pct": round(float(populated.mean()) * 100, 2),
        "value_kind": kind_mode,
        "v2_core": series.name in V2_CORE_FIELDS,
        "igdb_type": doc["igdb_type"],
        "igdb_description": doc["igdb_description"],
        "v2_note": doc["v2_note"],
    }

    if kind_mode == "string":
        lens = populated_s.astype(str).str.len()
        out["len_median"] = int(lens.median())
        out["len_p95"] = int(lens.quantile(0.95))
    elif kind_mode in {"integer", "float"}:
        nums = pd.to_numeric(populated_s, errors="coerce").dropna()
        if len(nums):
            out["min"] = float(nums.min())
            out["median"] = float(nums.median())
            out["max"] = float(nums.max())
    elif kind_mode == "id_list":
        lengths = populated_s.map(lambda v: len(_as_list(v)))
        out["list_len_median"] = float(lengths.median())
        out["list_len_p95"] = float(lengths.quantile(0.95))
        out["unique_ids"] = int(pd.Series([x for v in populated_s for x in _as_list(v)]).nunique())

    return out


def format_sample(value: Any, *, max_len: int = 240) -> str:
    if not field_populated(value):
        return "<empty>"
    if isinstance(value, str):
        text = value.replace("\n", " ")
        return text if len(text) <= max_len else text[: max_len - 3] + "..."
    if isinstance(value, np.ndarray):
        return f"array({value.tolist()})"
    return repr(value)[:max_len]


def display_field_profile(data: pd.DataFrame, field: str) -> None:
    series = data[field]
    prof = profile_column(series)
    doc = igdb_field_doc(field)
    v2_tag = " **V2_CORE**" if prof.get("v2_core") else ""
    dep_tag = " *(deprecated)*" if doc.get("deprecated") else ""
    display(Markdown(f"### `{field}`{v2_tag}{dep_tag}"))
    if doc.get("igdb_type"):
        display(Markdown(f"**IGDB type:** `{doc['igdb_type']}`"))
    if doc.get("igdb_description"):
        display(Markdown(f"**IGDB description:** {doc['igdb_description']}"))
    if doc.get("v2_note"):
        display(Markdown(f"**V2 note:** {doc['v2_note']}"))

    summary_rows = {
        k: v
        for k, v in prof.items()
        if k not in {"field", "igdb_type", "igdb_description", "v2_note", "v2_core"}
    }
    display(pd.DataFrame([summary_rows]))

    sample_df = (
        data.loc[data["app_id"].isin(SAMPLE_APP_IDS), ["app_id", "app_name", field]]
        .sort_values("app_id")
        .assign(sample=lambda d: d[field].map(format_sample))
        .drop(columns=[field])
    )
    display(sample_df)

    extra = data.loc[series.map(field_populated), field].head(3)
    print("Additional samples:")
    for app_id, val in zip(data.loc[extra.index, "app_id"], extra):
        print(f"  app_id={app_id}: {format_sample(val)}")

## Overview

In [4]:
overview = pd.DataFrame([profile_column(df[c]) for c in IGDB_GAME_FIELDS])
overview = overview.sort_values(["v2_core", "coverage_pct"], ascending=[False, False]).reset_index(drop=True)
display(overview)

display(overview.loc[overview["v2_core"], ["field", "coverage_pct", "value_kind", "igdb_type", "v2_note"]])

,field,dtype,coverage_pct,value_kind,v2_core,igdb_type,igdb_description,v2_note,list_len_median,list_len_p95,unique_ids,min,median,max,len_median,len_p95
0,game_modes,object,100.00,id_list,True,Array of Game Mode IDs,Modes of gameplay,V2a — Jaccard on game mode ID sets.,2.0,4.0,6.0,NaN,NaN,NaN,NaN,NaN
1,genres,object,100.00,id_list,True,Array of Genre IDs,Genres of the game,V2a — Jaccard on genre ID sets (entity lookup ...,3.0,5.0,20.0,NaN,NaN,NaN,NaN,NaN
2,summary,str,100.00,string,True,String,A description of the game,"V2b — USE dot(query_review, summary). Ready wi...",NaN,NaN,NaN,NaN,NaN,NaN,356.0,903.0
3,themes,object,98.41,id_list,True,Array of Theme IDs,Themes of the game,V2a — Jaccard on theme ID sets.,2.0,5.0,22.0,NaN,NaN,NaN,NaN,NaN
4,player_perspectives,object,96.18,id_list,True,Array of Player Perspective IDs,The main perspective of the player,V2a — Jaccard on perspective ID sets.,1.0,2.0,7.0,NaN,NaN,NaN,NaN,NaN
5,keywords,object,91.40,id_list,True,Array of Keyword IDs,Associated keywords,V2a — Jaccard on keyword ID sets; ~91% coverag...,12.0,84.0,1707.0,NaN,NaN,NaN,NaN,NaN
6,franchises,object,29.94,id_list,True,Array of Franchise IDs,Other franchises the game belongs to,V2a — Jaccard on franchise ID sets; sparse (~3...,1.0,2.0,91.0,NaN,NaN,NaN,NaN,NaN
7,checksum,str,100.00,string,False,uuid,Hash of the object,Audit / reproducibility only.,NaN,NaN,NaN,NaN,NaN,NaN,36.0,36.0
8,cover,int64,100.00,integer,False,Reference ID for Cover,The cover of this game,Media reference — not for text ranker.,NaN,NaN,NaN,2.884000e+03,1.149230e+05,5.701310e+05,NaN,NaN
9,created_at,int64,100.00,integer,False,datetime,Date this was initially added to the IGDB data...,IGDB record metadata.,NaN,NaN,NaN,1.297956e+09,1.467616e+09,1.675468e+09,NaN,NaN
10,external_games,object,100.00,id_list,False,Array of External Game IDs,External IDs this game has on other services,Store mapping IDs; join cross-check (Steam uid...,13.0,41.0,5154.0,NaN,NaN,NaN,NaN,NaN
11,first_release_date,int64,100.00,integer,False,Unix Time Stamp,The first release date for this game,Recency feature; unix timestamp.,NaN,NaN,NaN,9.114336e+08,1.506600e+09,1.750118e+09,NaN,NaN
12,game_type,int64,100.00,integer,False,Reference ID for Game Type,The type of game,Filter DLC/expansion/bundle noise before ranke...,NaN,NaN,NaN,0.000000e+00,0.000000e+00,1.100000e+01,NaN,NaN
13,platforms,object,100.00,id_list,False,Array of Platform IDs,Platforms this game was released on,Weak ranker signal; mostly PC on our Steam cat...,4.0,9.0,36.0,NaN,NaN,NaN,NaN,NaN
14,release_dates,object,100.00,id_list,False,Array of Release Date IDs,Release dates of this game,Platform/region-specific release metadata.,6.0,14.0,1913.0,NaN,NaN,NaN,NaN,NaN
15,screenshots,object,100.00,id_list,False,Array of Screenshot IDs,Screenshots of this game,Media reference.,7.0,18.0,2637.0,NaN,NaN,NaN,NaN,NaN
16,similar_games,object,100.00,id_list,False,Array of Game IDs,Similar games,Graph prior — IGDB game IDs; check overlap wit...,10.0,10.0,617.0,NaN,NaN,NaN,NaN,NaN
17,slug,str,100.00,string,False,String,"A url-safe, unique, lower-case version of the ...",Audit / join debug only.,NaN,NaN,NaN,NaN,NaN,NaN,15.0,32.0
18,tags,object,100.00,id_list,False,Array of Tag Numbers,Related entities in the IGDB API,V2a candidate — related-entity tag numbers; no...,16.0,91.0,1743.0,NaN,NaN,NaN,NaN,NaN
19,updated_at,int64,100.00,integer,False,datetime,The last date this entry was updated in the IG...,IGDB record metadata.,NaN,NaN,NaN,1.774581e+09,1.781666e+09,1.781733e+09,NaN,NaN
20,url,str,100.00,string,False,String,The website address (URL) of the item,Audit only.,NaN,NaN,NaN,NaN,NaN,NaN,42.0,59.0
21,websites,object,100.00,id_list,False,Array of Website IDs,Websites associated with this game,Media / link reference.,11.0,17.0,3388.0,NaN,NaN,NaN,NaN,NaN
22,involved_companies,object,99.36,id_list,False,Array of Involved Company IDs,Companies who developed this game,Developer/publisher IDs; optional metadata sig...,2.0,5.0,791.0,NaN,NaN,NaN,NaN,NaN
23,rating,float64,98.41,float,False,Double,Average IGDB user rating,Popularity proxy; likely redundant with D1 log...,NaN,NaN,NaN,2.025003e+01,7.807215e+01,9.382228e+01,NaN,NaN
24,rating_count,float64,98.41,float,False,Integer,Total number of IGDB user ratings,Support count for rating.,NaN,NaN,NaN,0.000000e+00,1.190000e+02,5.774000e+03,NaN,NaN
25,total_rating,float64,98.41,float,False,Double,Average rating based on both IGDB user and ext...,Blended IGDB + critic rating.,NaN,NaN,NaN,2.829168e+01,7.863212e+01,9.278971e+01,NaN,NaN
26,total_rating_count,float64,98.41,float,False,Integer,Total number of user and external critic scores,Support count for total_rating.,NaN,NaN,NaN,0.000000e+00,1.290000e+02,5.801000e+03,NaN,NaN
27,artworks,object,97.77,id_list,False,Array of Artwork IDs,Artworks of this game,Media reference.,1.0,12.0,846.0,NaN,NaN,NaN,NaN,NaN
28,language_supports,object,97.13,id_list,False,Array of Language Support IDs,Supported languages for this game,Localization IDs.,19.0,43.8,6038.0,NaN,NaN,NaN,NaN,NaN
29,videos,object,95.86,id_list,False,Array of Game Video IDs,Videos of this game,Media reference.,3.0,13.0,1257.0,NaN,NaN,NaN,NaN,NaN
30,alternative_names,object,90.76,id_list,False,Array of Alternative Name IDs,Alternative names for this game,,2.0,7.0,770.0,NaN,NaN,NaN,NaN,NaN
31,age_ratings,object,85.35,id_list,False,Array of Age Rating IDs,The PEGI rating,,5.0,7.0,1327.0,NaN,NaN,NaN,NaN,NaN
32,aggregated_rating,float64,81.21,float,False,Double,Rating based on external critic scores,,NaN,NaN,NaN,0.000000e+00,8.133333e+01,9.638462e+01,NaN,NaN
33,aggregated_rating_count,float64,81.21,float,False,Integer,Number of external critic scores,,NaN,NaN,NaN,0.000000e+00,8.000000e+00,3.800000e+01,NaN,NaN
34,game_engines,object,78.34,id_list,False,Array of Game Engine IDs,The game engine used in this game,,1.0,1.0,102.0,NaN,NaN,NaN,NaN,NaN
35,collections,object,65.29,id_list,False,Array of Collection IDs,The collections that this game is in,,1.0,1.8,183.0,NaN,NaN,NaN,NaN,NaN
36,hypes,float64,62.10,float,False,Integer,Number of follows a game gets before release,,NaN,NaN,NaN,1.000000e+00,5.000000e+00,2.820000e+02,NaN,NaN
37,game_localizations,object,58.60,id_list,False,Array of Game Localization IDs,Supported game localizations for this game. A ...,,1.0,2.0,270.0,NaN,NaN,NaN,NaN,NaN
38,storyline,str,49.68,string,False,String,A short description of a game's story,Extra text field (not summary); ~50% coverage;...,NaN,NaN,NaN,NaN,NaN,NaN,568.0,2606.0
39,bundles,object,44.59,id_list,False,Array of Game IDs,The bundles this game is a part of,,1.0,6.0,269.0,NaN,NaN,NaN,NaN,NaN
40,multiplayer_modes,object,41.40,id_list,False,Array of Multiplayer Mode IDs,Multiplayer modes for this game,,1.0,3.0,196.0,NaN,NaN,NaN,NaN,NaN
41,dlcs,object,39.81,id_list,False,Array of Game IDs,DLCs for this game,,3.0,22.0,1134.0,NaN,NaN,NaN,NaN,NaN
42,expansions,object,18.47,id_list,False,Array of Game IDs,Expansions of this game,,2.0,14.0,203.0,NaN,NaN,NaN,NaN,NaN
43,ports,object,9.55,id_list,False,Array of Game IDs,Ports of this game,,1.0,4.1,46.0,NaN,NaN,NaN,NaN,NaN
44,parent_game,float64,6.69,float,False,Reference ID for Game,"If a DLC, expansion or part of a bundle, this ...",,NaN,NaN,NaN,2.310000e+02,2.985000e+03,2.255650e+05,NaN,NaN
45,game_status,float64,5.73,float,False,Reference ID for Game Status,The status of the game's release,,NaN,NaN,NaN,4.000000e+00,4.000000e+00,8.000000e+00,NaN,NaN
46,status,float64,5.73,float,False,Status Enum,DEPRECATED — use game_status instead,,NaN,NaN,NaN,4.000000e+00,4.000000e+00,8.000000e+00,NaN,NaN
47,remasters,object,5.41,id_list,False,Array of Game IDs,Remasters of this game,,1.0,1.0,17.0,NaN,NaN,NaN,NaN,NaN
48,expanded_games,object,4.46,id_list,False,Array of Game IDs,Expanded games of this game,,1.0,1.0,14.0,NaN,NaN,NaN,NaN,NaN
49,standalone_expansions,object,4.14,id_list,False,Array of Game IDs,Standalone expansions of this game,,1.0,2.4,16.0,NaN,NaN,NaN,NaN,NaN
50,franchise,float64,3.82,float,False,Reference ID for Franchise,The main franchise,,NaN,NaN,NaN,4.000000e+00,3.350000e+01,4.250000e+02,NaN,NaN
51,remakes,object,1.59,id_list,False,Array of Game IDs,Remakes of this game,,1.0,1.8,6.0,NaN,NaN,NaN,NaN,NaN
52,version_parent,float64,1.27,float,False,Reference ID for Game,"If a version, this is the main game",,NaN,NaN,NaN,5.000000e+02,4.901500e+03,1.257100e+04,NaN,NaN
53,version_title,str,1.27,string,False,String,Title of this version (i.e. Gold edition),,NaN,NaN,NaN,NaN,NaN,NaN,15.0,22.0

,field,coverage_pct,value_kind,igdb_type,v2_note
0,game_modes,100.00,id_list,Array of Game Mode IDs,V2a — Jaccard on game mode ID sets.
1,genres,100.00,id_list,Array of Genre IDs,V2a — Jaccard on genre ID sets (entity lookup ...
2,summary,100.00,string,String,"V2b — USE dot(query_review, summary). Ready wi..."
3,themes,98.41,id_list,Array of Theme IDs,V2a — Jaccard on theme ID sets.
4,player_perspectives,96.18,id_list,Array of Player Perspective IDs,V2a — Jaccard on perspective ID sets.
5,keywords,91.40,id_list,Array of Keyword IDs,V2a — Jaccard on keyword ID sets; ~91% coverag...
6,franchises,29.94,id_list,Array of Franchise IDs,V2a — Jaccard on franchise ID sets; sparse (~3...

## Per-field review

One subsection per IGDB game column.

In [5]:
for field in IGDB_GAME_FIELDS:
    display_field_profile(df, field)
    print()

### `age_ratings`

**IGDB type:** `Array of Age Rating IDs`

**IGDB description:** The PEGI rating

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         85.35    id_list              5.0           7.0        1327

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([125538, 195813, 39086, 181520, 57827, 1...
1  646910        The Crew 2  array([111035, 111034, 91834, 92244, 215725, 2...
0  753420          Dungreed              array([119531, 55417, 98238, 187890])

Additional samples:
  app_id=753420: array([119531, 55417, 98238, 187890])
  app_id=646910: array([111035, 111034, 91834, 92244, 215725, 215726, 25509])
  app_id=512900: array([125538, 195813, 39086, 181520, 57827, 120997])

### `aggregated_rating`

**IGDB type:** `Double`

**IGDB description:** Rating based on external critic scores

     dtype  coverage_pct value_kind  min     median        max
0  float64         81.21      float  0.0  81.333333  96.384615

   app_id          app_name   sample
2  512900  Streets of Rogue     84.0
1  646910        The Crew 2     62.3
0  753420          Dungreed  <empty>

Additional samples:
  app_id=646910: 62.3
  app_id=512900: 84.0
  app_id=637090: 82.25

### `aggregated_rating_count`

**IGDB type:** `Integer`

**IGDB description:** Number of external critic scores

     dtype  coverage_pct value_kind  min  median   max
0  float64         81.21      float  0.0     8.0  38.0

   app_id          app_name   sample
2  512900  Streets of Rogue      1.0
1  646910        The Crew 2     10.0
0  753420          Dungreed  <empty>

Additional samples:
  app_id=646910: 10.0
  app_id=512900: 1.0
  app_id=637090: 8.0

### `alternative_names`

**IGDB type:** `Array of Alternative Name IDs`

**IGDB description:** Alternative names for this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         90.76    id_list              2.0           7.0         770

   app_id          app_name                          sample
2  512900  Streets of Rogue                 array([178999])
1  646910        The Crew 2         array([103431, 193381])
0  753420          Dungreed  array([50098, 111807, 201736])

Additional samples:
  app_id=753420: array([50098, 111807, 201736])
  app_id=646910: array([103431, 193381])
  app_id=512900: array([178999])

### `artworks`

**IGDB type:** `Array of Artwork IDs`

**IGDB description:** Artworks of this game

**V2 note:** Media reference.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         97.77    id_list              1.0          12.0         846

   app_id          app_name              sample
2  512900  Streets of Rogue      array([10949])
1  646910        The Crew 2  array([465, 5828])
0  753420          Dungreed      array([16931])

Additional samples:
  app_id=753420: array([16931])
  app_id=646910: array([465, 5828])
  app_id=512900: array([10949])

### `bundles`

**IGDB type:** `Array of Game IDs`

**IGDB description:** The bundles this game is a part of

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         44.59    id_list              1.0           6.0         269

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=637090: array([155213])
  app_id=748490: array([201066])
  app_id=825630: array([113475])

### `checksum`

**IGDB type:** `uuid`

**IGDB description:** Hash of the object

**V2 note:** Audit / reproducibility only.

  dtype  coverage_pct value_kind  len_median  len_p95
0   str         100.0     string          36       36

   app_id          app_name                                sample
2  512900  Streets of Rogue  3eea4965-333f-545c-5ced-57ebbf374b5e
1  646910        The Crew 2  dddbc7c1-c1f0-6967-24e9-9a24c5930f3d
0  753420          Dungreed  86de8aaa-d069-6b51-66ad-206cf819975b

Additional samples:
  app_id=753420: 86de8aaa-d069-6b51-66ad-206cf819975b
  app_id=646910: dddbc7c1-c1f0-6967-24e9-9a24c5930f3d
  app_id=512900: 3eea4965-333f-545c-5ced-57ebbf374b5e

### `collections`

**IGDB type:** `Array of Collection IDs`

**IGDB description:** The collections that this game is in

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         65.29    id_list              1.0           1.8         183

   app_id          app_name          sample
2  512900  Streets of Rogue  array([11919])
1  646910        The Crew 2   array([2719])
0  753420          Dungreed         <empty>

Additional samples:
  app_id=646910: array([2719])
  app_id=512900: array([11919])
  app_id=637090: array([2091])

### `cover`

**IGDB type:** `Reference ID for Cover`

**IGDB description:** The cover of this game

**V2 note:** Media reference — not for text ranker.

   dtype  coverage_pct value_kind     min    median       max
0  int64         100.0    integer  2884.0  114923.0  570131.0

   app_id          app_name  sample
2  512900  Streets of Rogue   82075
1  646910        The Crew 2  481020
0  753420          Dungreed   87917

Additional samples:
  app_id=753420: 87917
  app_id=646910: 481020
  app_id=512900: 82075

### `created_at`

**IGDB type:** `datetime`

**IGDB description:** Date this was initially added to the IGDB database

**V2 note:** IGDB record metadata.

   dtype  coverage_pct value_kind           min        median           max
0  int64         100.0    integer  1.297956e+09  1.467616e+09  1.675468e+09

   app_id          app_name      sample
2  512900  Streets of Rogue  1472625697
1  646910        The Crew 2  1494997767
0  753420          Dungreed  1512575158

Additional samples:
  app_id=753420: 1512575158
  app_id=646910: 1494997767
  app_id=512900: 1472625697

### `dlcs`

**IGDB type:** `Array of Game IDs`

**IGDB description:** DLCs for this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         39.81    id_list              3.0          22.0        1134

   app_id          app_name           sample
2  512900  Streets of Rogue  array([196279])
1  646910        The Crew 2          <empty>
0  753420          Dungreed          <empty>

Additional samples:
  app_id=512900: array([196279])
  app_id=637090: array([155212, 155087])
  app_id=748490: array([124812])

### `expanded_games`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Expanded games of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          4.46    id_list              1.0           1.0          14

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=420530: array([200905])
  app_id=271590: array([334254])
  app_id=489830: array([165192])

### `expansions`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Expansions of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         18.47    id_list              2.0          14.0         203

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=637090: array([107258])
  app_id=39210: array([14723, 259338, 112412, 143232, 26625, 399337])
  app_id=648350: array([140515])

### `external_games`

**IGDB type:** `Array of External Game IDs`

**IGDB description:** External IDs this game has on other services

**V2 note:** Store mapping IDs; join cross-check (Steam uid in pass 1).

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list             13.0          41.0        5154

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([1476119, 75623, 109462, 251243, 2173930...
1  646910        The Crew 2  array([1935153, 1930311, 1936603, 1928638, 192...
0  753420          Dungreed  array([576824, 1685524, 1597044, 2651238, 2584...

Additional samples:
  app_id=753420: array([576824, 1685524, 1597044, 2651238, 2584948, 2581943, 2171354, 2657002, 191130, 2598579, 253660])
  app_id=646910: array([1935153, 1930311, 1936603, 1928638, 1928548, 75847, 94338, 94337, 1237138, 398273, 83565, 1930561, 2698123, 1200554, 2175616, 1931870, 1937341, 1936524, 1938033, 1938243, 102434, 210992, 3142009, 2688263, 2586711, 1184683, 2590574, 1930154, 2085885, 2085048, 2627425, 2604597, 2677553, 2589288, 2084937, 2586821, 2586981, 2085901, 253592])
  app_id=512900: array([1476119, 75623, 109462, 251243, 2173930, 2603612, 2082059, 2661922, 2182095, 3576, 2133742, 2069429])

### `first_release_date`

**IGDB type:** `Unix Time Stamp`

**IGDB description:** The first release date for this game

**V2 note:** Recency feature; unix timestamp.

   dtype  coverage_pct value_kind          min        median           max
0  int64         100.0    integer  911433600.0  1.506600e+09  1.750118e+09

   app_id          app_name      sample
2  512900  Streets of Rogue  1562803200
1  646910        The Crew 2  1530230400
0  753420          Dungreed  1518566400

Additional samples:
  app_id=753420: 1518566400
  app_id=646910: 1530230400
  app_id=512900: 1562803200

### `franchise`

**IGDB type:** `Reference ID for Franchise`

**IGDB description:** The main franchise

     dtype  coverage_pct value_kind  min  median    max
0  float64          3.82      float  4.0    33.5  425.0

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=39210: 4.0
  app_id=637650: 4.0
  app_id=362890: 425.0

### `franchises` **V2_CORE**

**IGDB type:** `Array of Franchise IDs`

**IGDB description:** Other franchises the game belongs to

**V2 note:** V2a — Jaccard on franchise ID sets; sparse (~30% coverage) on our catalog.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         29.94    id_list              1.0           2.0          91

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=613830: array([1844])
  app_id=748490: array([855])
  app_id=825630: array([842])

### `game_engines`

**IGDB type:** `Array of Game Engine IDs`

**IGDB description:** The game engine used in this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         78.34    id_list              1.0           1.0         102

   app_id          app_name        sample
2  512900  Streets of Rogue   array([13])
1  646910        The Crew 2  array([118])
0  753420          Dungreed   array([13])

Additional samples:
  app_id=753420: array([13])
  app_id=646910: array([118])
  app_id=512900: array([13])

### `game_localizations`

**IGDB type:** `Array of Game Localization IDs`

**IGDB description:** Supported game localizations for this game. A region can have at most one game localization for a given game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          58.6    id_list              1.0           2.0         270

   app_id          app_name                sample
2  512900  Streets of Rogue               <empty>
1  646910        The Crew 2   array([1868, 6582])
0  753420          Dungreed  array([9836, 20498])

Additional samples:
  app_id=753420: array([9836, 20498])
  app_id=646910: array([1868, 6582])
  app_id=613830: array([360, 25886])

### `game_modes` **V2_CORE**

**IGDB type:** `Array of Game Mode IDs`

**IGDB description:** Modes of gameplay

**V2 note:** V2a — Jaccard on game mode ID sets.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list              2.0           4.0           6

   app_id          app_name               sample
2  512900  Streets of Rogue  array([1, 2, 3, 4])
1  646910        The Crew 2  array([1, 2, 3, 5])
0  753420          Dungreed           array([1])

Additional samples:
  app_id=753420: array([1])
  app_id=646910: array([1, 2, 3, 5])
  app_id=512900: array([1, 2, 3, 4])

### `game_status`

**IGDB type:** `Reference ID for Game Status`

**IGDB description:** The status of the game's release

     dtype  coverage_pct value_kind  min  median  max
0  float64          5.73      float  4.0     4.0  8.0

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=753650: 4.0
  app_id=739630: 4.0
  app_id=420: 8.0

### `game_type`

**IGDB type:** `Reference ID for Game Type`

**IGDB description:** The type of game

**V2 note:** Filter DLC/expansion/bundle noise before ranker features.

   dtype  coverage_pct value_kind  min  median   max
0  int64         100.0    integer  0.0     0.0  11.0

   app_id          app_name sample
2  512900  Streets of Rogue      0
1  646910        The Crew 2      0
0  753420          Dungreed      0

Additional samples:
  app_id=753420: 0
  app_id=646910: 0
  app_id=512900: 0

### `genres` **V2_CORE**

**IGDB type:** `Array of Genre IDs`

**IGDB description:** Genres of the game

**V2 note:** V2a — Jaccard on genre ID sets (entity lookup optional for human QA).

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list              3.0           5.0          20

   app_id          app_name                      sample
2  512900  Streets of Rogue  array([5, 12, 25, 31, 32])
1  646910        The Crew 2                 array([10])
0  753420          Dungreed          array([8, 31, 32])

Additional samples:
  app_id=753420: array([8, 31, 32])
  app_id=646910: array([10])
  app_id=512900: array([5, 12, 25, 31, 32])

### `hypes`

**IGDB type:** `Integer`

**IGDB description:** Number of follows a game gets before release

     dtype  coverage_pct value_kind  min  median    max
0  float64          62.1      float  1.0     5.0  282.0

   app_id          app_name sample
2  512900  Streets of Rogue    6.0
1  646910        The Crew 2   18.0
0  753420          Dungreed    1.0

Additional samples:
  app_id=753420: 1.0
  app_id=646910: 18.0
  app_id=512900: 6.0

### `involved_companies`

**IGDB type:** `Array of Involved Company IDs`

**IGDB description:** Companies who developed this game

**V2 note:** Developer/publisher IDs; optional metadata signal.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         99.36    id_list              2.0           5.0         791

   app_id          app_name                           sample
2  512900  Streets of Rogue  array([116692, 116693, 277284])
1  646910        The Crew 2   array([50782, 141206, 202299])
0  753420          Dungreed           array([72008, 128578])

Additional samples:
  app_id=753420: array([72008, 128578])
  app_id=646910: array([50782, 141206, 202299])
  app_id=512900: array([116692, 116693, 277284])

### `keywords` **V2_CORE**

**IGDB type:** `Array of Keyword IDs`

**IGDB description:** Associated keywords

**V2 note:** V2a — Jaccard on keyword ID sets; ~91% coverage on our catalog.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          91.4    id_list             12.0          84.0        1707

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([416, 577, 1033, 1980, 4154, 4466, 4882,...
1  646910        The Crew 2                 array([155, 613, 778, 2071, 4357])
0  753420          Dungreed                                            <empty>

Additional samples:
  app_id=646910: array([155, 613, 778, 2071, 4357])
  app_id=512900: array([416, 577, 1033, 1980, 4154, 4466, 4882, 17292, 26969])
  app_id=637090: array([69, 167, 415, 575, 1107, 1317, 1379, 1448, 2425, 4134, 4248, 4250, 4272, 4882, 4886, 5323, 5379, 5453, 6304, 6699, 9357, 49331])

### `language_supports`

**IGDB type:** `Array of Language Support IDs`

**IGDB description:** Supported languages for this game

**V2 note:** Localization IDs.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         97.13    id_list             19.0          43.8        6038

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([92927, 92928, 92929, 92930, 92931, 9293...
1  646910        The Crew 2  array([27007, 27008, 26998, 26999, 27000, 2700...
0  753420          Dungreed  array([175256, 175265, 175257, 175260, 175261,...

Additional samples:
  app_id=753420: array([175256, 175265, 175257, 175260, 175261, 175263, 175264, 175266, 175267, 175269, 175270, 175271, 175253, 175254, 175255, 175258, 175259, 175268, 175262])
  app_id=646910: array([27007, 27008, 26998, 26999, 27000, 27002, 26974, 26979, 27003, 26995, 27004, 26977, 26980, 26982, 26989, 26993, 26996, 26973, 26990, 26992, 26997, 27001, 26976, 26987, 26991, 26994, 27006, 26978, 26975, 26981, 27005, 26983, 26984, 26986, 26985, 26988, 205956, 205957, 205958])
  app_id=512900: array([92927, 92928, 92929, 92930, 92931, 92932, 92933, 92934, 92935, 92936, 92937, 92938, 92939, 92941, 92940, 92942, 499286])

### `multiplayer_modes`

**IGDB type:** `Array of Multiplayer Mode IDs`

**IGDB description:** Multiplayer modes for this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          41.4    id_list              1.0           3.0         196

   app_id          app_name         sample
2  512900  Streets of Rogue  array([3937])
1  646910        The Crew 2  array([8291])
0  753420          Dungreed        <empty>

Additional samples:
  app_id=646910: array([8291])
  app_id=512900: array([3937])
  app_id=214950: array([7273])

### `parent_game`

**IGDB type:** `Reference ID for Game`

**IGDB description:** If a DLC, expansion or part of a bundle, this is the main game or bundle

     dtype  coverage_pct value_kind    min  median       max
0  float64          6.69      float  231.0  2985.0  225565.0

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=613830: 89828.0
  app_id=420530: 225565.0
  app_id=570940: 2155.0

### `platforms`

**IGDB type:** `Array of Platform IDs`

**IGDB description:** Platforms this game was released on

**V2 note:** Weak ranker signal; mostly PC on our Steam catalog.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list              4.0           9.0          36

   app_id          app_name                          sample
2  512900  Streets of Rogue  array([48, 3, 6, 14, 49, 130])
1  646910        The Crew 2         array([170, 48, 6, 49])
0  753420          Dungreed      array([48, 3, 6, 14, 130])

Additional samples:
  app_id=753420: array([48, 3, 6, 14, 130])
  app_id=646910: array([170, 48, 6, 49])
  app_id=512900: array([48, 3, 6, 14, 49, 130])

### `player_perspectives` **V2_CORE**

**IGDB type:** `Array of Player Perspective IDs`

**IGDB description:** The main perspective of the player

**V2 note:** V2a — Jaccard on perspective ID sets.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         96.18    id_list              1.0           2.0           7

   app_id          app_name      sample
2  512900  Streets of Rogue  array([3])
1  646910        The Crew 2  array([2])
0  753420          Dungreed  array([4])

Additional samples:
  app_id=753420: array([4])
  app_id=646910: array([2])
  app_id=512900: array([3])

### `ports`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Ports of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          9.55    id_list              1.0           4.1          46

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=39210: array([322502])
  app_id=40800: array([77316])
  app_id=323190: array([199959, 117420])

### `rating`

**IGDB type:** `Double`

**IGDB description:** Average IGDB user rating

**V2 note:** Popularity proxy; likely redundant with D1 log-pop blend.

     dtype  coverage_pct value_kind        min     median        max
0  float64         98.41      float  20.250033  78.072147  93.822278

   app_id          app_name             sample
2  512900  Streets of Rogue  65.27215198485874
1  646910        The Crew 2   73.9770528561776
0  753420          Dungreed  50.76393181851428

Additional samples:
  app_id=753420: 50.76393181851428
  app_id=646910: 73.9770528561776
  app_id=512900: 65.27215198485874

### `rating_count`

**IGDB type:** `Integer`

**IGDB description:** Total number of IGDB user ratings

**V2 note:** Support count for rating.

     dtype  coverage_pct value_kind  min  median     max
0  float64         98.41      float  0.0   119.0  5774.0

   app_id          app_name sample
2  512900  Streets of Rogue   46.0
1  646910        The Crew 2  113.0
0  753420          Dungreed    6.0

Additional samples:
  app_id=753420: 6.0
  app_id=646910: 113.0
  app_id=512900: 46.0

### `release_dates`

**IGDB type:** `Array of Release Date IDs`

**IGDB description:** Release dates of this game

**V2 note:** Platform/region-specific release metadata.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list              6.0          14.0        1913

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([348221, 338956, 171918, 171915, 171916,...
1  646910        The Crew 2            array([149099, 239577, 149097, 149098])
0  753420          Dungreed  array([418336, 418337, 342005, 418338, 219416,...

Additional samples:
  app_id=753420: array([418336, 418337, 342005, 418338, 219416, 219417])
  app_id=646910: array([149099, 239577, 149097, 149098])
  app_id=512900: array([348221, 338956, 171918, 171915, 171916, 171917, 171919])

### `remakes`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Remakes of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          1.59    id_list              1.0           1.8           6

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=239030: array([260929])
  app_id=1128000: array([376012])
  app_id=70: array([6739])

### `remasters`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Remasters of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          5.41    id_list              1.0           1.0          17

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=748490: array([78114])
  app_id=323190: array([341662])
  app_id=214560: array([94969])

### `screenshots`

**IGDB type:** `Array of Screenshot IDs`

**IGDB description:** Screenshots of this game

**V2 note:** Media reference.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list              7.0          18.0        2637

   app_id          app_name                                             sample
2  512900  Streets of Rogue         array([30967, 30968, 30966, 30965, 30969])
1  646910        The Crew 2  array([256136, 44289, 211048, 44288, 44290, 44...
0  753420          Dungreed    array([138718, 138719, 138717, 138715, 138716])

Additional samples:
  app_id=753420: array([138718, 138719, 138717, 138715, 138716])
  app_id=646910: array([256136, 44289, 211048, 44288, 44290, 44291, 44292, 211044, 211046, 211047, 211045, 256137, 1379606, 1379607, 1379608, 1381106, 1381107, 1381108])
  app_id=512900: array([30967, 30968, 30966, 30965, 30969])

### `similar_games`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Similar games

**V2 note:** Graph prior — IGDB game IDs; check overlap with our catalog index.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list             10.0          10.0         617

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([47823, 36198, 28309, 80916, 18869, 1916...
1  646910        The Crew 2  array([119161, 3772, 37419, 105011, 36662, 812...
0  753420          Dungreed  array([111130, 20342, 55173, 106987, 28309, 24...

Additional samples:
  app_id=753420: array([111130, 20342, 55173, 106987, 28309, 24426, 113895, 28070, 25646, 89597])
  app_id=646910: array([119161, 3772, 37419, 105011, 36662, 81249, 27092, 19164, 19541, 26574])
  app_id=512900: array([47823, 36198, 28309, 80916, 18869, 19164, 19150, 105269, 10776, 18290])

### `slug`

**IGDB type:** `String`

**IGDB description:** A url-safe, unique, lower-case version of the name

**V2 note:** Audit / join debug only.

  dtype  coverage_pct value_kind  len_median  len_p95
0   str         100.0     string          15       32

   app_id          app_name            sample
2  512900  Streets of Rogue  streets-of-rogue
1  646910        The Crew 2        the-crew-2
0  753420          Dungreed          dungreed

Additional samples:
  app_id=753420: dungreed
  app_id=646910: the-crew-2
  app_id=512900: streets-of-rogue

### `standalone_expansions`

**IGDB type:** `Array of Game IDs`

**IGDB description:** Standalone expansions of this game

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object          4.14    id_list              1.0           2.4          16

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=420530: array([307795])
  app_id=271590: array([134710])
  app_id=960090: array([153002])

### `status` *(deprecated)*

**IGDB type:** `Status Enum`

**IGDB description:** DEPRECATED — use game_status instead

     dtype  coverage_pct value_kind  min  median  max
0  float64          5.73      float  4.0     4.0  8.0

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=753650: 4.0
  app_id=739630: 4.0
  app_id=420: 8.0

### `storyline`

**IGDB type:** `String`

**IGDB description:** A short description of a game's story

**V2 note:** Extra text field (not summary); ~50% coverage; optional V2b supplement.

  dtype  coverage_pct value_kind  len_median  len_p95
0   str         49.68     string         568     2606

   app_id          app_name                                             sample
2  512900  Streets of Rogue                                            <empty>
1  646910        The Crew 2  The game features a nonlinear story, that foll...
0  753420          Dungreed                                            <empty>

Additional samples:
  app_id=646910: The game features a nonlinear story, that follows the unnamed player character as they become a racing icon in the United States by winning in all racing disciplines available in the game. There are four disciplines: Street Racing, Off R...
  app_id=613830: A chance encounter amid the festivities of Guardia's Millennial Fair in Leene Square introduces our young hero, Crono, to a girl by the name of Marle. Deciding to explore the fair together, the two soon find themselves at an exhibition o...
  app_id=748490: The Legend of Heroes: Trails of Cold Steel II picks up one month after the decisive collision that changed the fate of the entire nation of Erebonia. The speedy, tactical turn-based combat with the newly-developed “ARCUS” system returns,...

### `summary` **V2_CORE**

**IGDB type:** `String`

**IGDB description:** A description of the game

**V2 note:** V2b — USE dot(query_review, summary). Ready without entity lookup.

  dtype  coverage_pct value_kind  len_median  len_p95
0   str         100.0     string         356      903

   app_id          app_name                                             sample
2  512900  Streets of Rogue  Streets of Rogue is a top-down rogue-lite with...
1  646910        The Crew 2  The newest iteration in the revolutionary fran...
0  753420          Dungreed  Dungreed is 2D side-scrolling action game with...

Additional samples:
  app_id=753420: Dungreed is 2D side-scrolling action game with a Rogue-LITE element. You'll explore the ever-changing dungeon that destroyed everything in the village. Kill enemies, Use various weapons, spells, and eat food to defeat evil in the dungeon!
  app_id=646910: The newest iteration in the revolutionary franchise, The Crew 2 captures the thrill of the American motorsports spirit in one of the most exhilarating open worlds ever created. Welcome to Motornation, a huge, varied, action-packed, and b...
  app_id=512900: Streets of Rogue is a top-down rogue-lite with an emphasis on player agency and freedom. It combines shooting, stealth, and role-playing elements in a procedurally generated city.  Rather than taking place in a dungeon, the game is set i...

### `tags`

**IGDB type:** `Array of Tag Numbers`

**IGDB description:** Related entities in the IGDB API

**V2 note:** V2a candidate — related-entity tag numbers; noisier than genres/themes.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list             16.0          91.0        1743

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([1, 23, 27, 33, 268435461, 268435468, 26...
1  646910        The Crew 2  array([1, 38, 268435466, 536871067, 536871525,...
0  753420          Dungreed        array([1, 268435464, 268435487, 268435488])

Additional samples:
  app_id=753420: array([1, 268435464, 268435487, 268435488])
  app_id=646910: array([1, 38, 268435466, 536871067, 536871525, 536871690, 536872983, 536875269])
  app_id=512900: array([1, 23, 27, 33, 268435461, 268435468, 268435481, 268435487, 268435488, 536871328, 536871489, 536871945, 536872892, 536875066, 536875378, 536875794, 536888204, 536897881])

### `themes` **V2_CORE**

**IGDB type:** `Array of Theme IDs`

**IGDB description:** Themes of the game

**V2 note:** V2a — Jaccard on theme ID sets.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         98.41    id_list              2.0           5.0          22

   app_id          app_name                  sample
2  512900  Streets of Rogue  array([1, 23, 27, 33])
1  646910        The Crew 2          array([1, 38])
0  753420          Dungreed              array([1])

Additional samples:
  app_id=753420: array([1])
  app_id=646910: array([1, 38])
  app_id=512900: array([1, 23, 27, 33])

### `total_rating`

**IGDB type:** `Double`

**IGDB description:** Average rating based on both IGDB user and external critic scores

**V2 note:** Blended IGDB + critic rating.

     dtype  coverage_pct value_kind        min     median        max
0  float64         98.41      float  28.291683  78.632117  92.789712

   app_id          app_name             sample
2  512900  Streets of Rogue  74.63607599242937
1  646910        The Crew 2   68.1385264280888
0  753420          Dungreed  50.76393181851428

Additional samples:
  app_id=753420: 50.76393181851428
  app_id=646910: 68.1385264280888
  app_id=512900: 74.63607599242937

### `total_rating_count`

**IGDB type:** `Integer`

**IGDB description:** Total number of user and external critic scores

**V2 note:** Support count for total_rating.

     dtype  coverage_pct value_kind  min  median     max
0  float64         98.41      float  0.0   129.0  5801.0

   app_id          app_name sample
2  512900  Streets of Rogue   47.0
1  646910        The Crew 2  123.0
0  753420          Dungreed    6.0

Additional samples:
  app_id=753420: 6.0
  app_id=646910: 123.0
  app_id=512900: 47.0

### `updated_at`

**IGDB type:** `datetime`

**IGDB description:** The last date this entry was updated in the IGDB database

**V2 note:** IGDB record metadata.

   dtype  coverage_pct value_kind           min        median           max
0  int64         100.0    integer  1.774581e+09  1.781666e+09  1.781733e+09

   app_id          app_name      sample
2  512900  Streets of Rogue  1781635159
1  646910        The Crew 2  1781665519
0  753420          Dungreed  1781580383

Additional samples:
  app_id=753420: 1781580383
  app_id=646910: 1781665519
  app_id=512900: 1781635159

### `url`

**IGDB type:** `String`

**IGDB description:** The website address (URL) of the item

**V2 note:** Audit only.

  dtype  coverage_pct value_kind  len_median  len_p95
0   str         100.0     string          42       59

   app_id          app_name                                       sample
2  512900  Streets of Rogue  https://www.igdb.com/games/streets-of-rogue
1  646910        The Crew 2        https://www.igdb.com/games/the-crew-2
0  753420          Dungreed          https://www.igdb.com/games/dungreed

Additional samples:
  app_id=753420: https://www.igdb.com/games/dungreed
  app_id=646910: https://www.igdb.com/games/the-crew-2
  app_id=512900: https://www.igdb.com/games/streets-of-rogue

### `version_parent`

**IGDB type:** `Reference ID for Game`

**IGDB description:** If a version, this is the main game

     dtype  coverage_pct value_kind    min  median      max
0  float64          1.27      float  500.0  4901.5  12571.0

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=214950: 2359.0
  app_id=485510: 12571.0
  app_id=35140: 500.0

### `version_title`

**IGDB type:** `String`

**IGDB description:** Title of this version (i.e. Gold edition)

  dtype  coverage_pct value_kind  len_median  len_p95
0   str          1.27     string          15       22

   app_id          app_name   sample
2  512900  Streets of Rogue  <empty>
1  646910        The Crew 2  <empty>
0  753420          Dungreed  <empty>

Additional samples:
  app_id=214950: Emperor Edition
  app_id=485510: Complete Edition
  app_id=35140: Game of the Year Edition

### `videos`

**IGDB type:** `Array of Game Video IDs`

**IGDB description:** Videos of this game

**V2 note:** Media reference.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         95.86    id_list              3.0          13.0        1257

   app_id          app_name                                             sample
2  512900  Streets of Rogue                               array([12641, 9619])
1  646910        The Crew 2  array([20627, 14589, 14588, 20372, 15597, 18681])
0  753420          Dungreed                                     array([32665])

Additional samples:
  app_id=753420: array([32665])
  app_id=646910: array([20627, 14589, 14588, 20372, 15597, 18681])
  app_id=512900: array([12641, 9619])

### `websites`

**IGDB type:** `Array of Website IDs`

**IGDB description:** Websites associated with this game

**V2 note:** Media / link reference.

    dtype  coverage_pct value_kind  list_len_median  list_len_p95  unique_ids
0  object         100.0    id_list             11.0          17.0        3388

   app_id          app_name                                             sample
2  512900  Streets of Rogue  array([831925, 761475, 761476, 110813, 16428, ...
1  646910        The Crew 2  array([63721, 312584, 833260, 833259, 833261, ...
0  753420          Dungreed  array([920873, 920874, 756045, 756041, 520086,...

Additional samples:
  app_id=753420: array([920873, 920874, 756045, 756041, 520086, 128835, 63833, 128836, 340645, 520085])
  app_id=646910: array([63721, 312584, 833260, 833259, 833261, 833262, 63719, 63722, 312583, 340578, 39649, 63723, 63720])
  app_id=512900: array([831925, 761475, 761476, 110813, 16428, 121120, 236719, 338319, 655211, 16429, 16427])